Features/mukhamadeev page
stpracticejob/job_2022 pull request #17
Opened 2022-05-20 13:42 UTC by Vendigo74

Добавил фронт страницы с табличкой пользователей, Добавил бутстраповскую шапку для неавторизованного пользователя.

2022-05-20 14:43 UTC, sergeybe2 requested changes

2022-05-21 09:23 UTC, MikhailSalkov commented on src/Database.php
> +        $stmt = $this->prepare('SELECT ID, UserName, Login, Password, RoleID, State FROM users WHERE ID = :id LIMIT 1');
Здесь пароль тоже не к чему

2022-05-21 09:23 UTC, MikhailSalkov commented on src/Database.php
> +        $stmt = $this->prepare('SELECT ID, UserName, Login, Password, RoleID, State FROM users WHERE ID = :id LIMIT 1');
Здесь пароль тоже не к чему

2022-05-21 09:32 UTC, MikhailSalkov requested changes
Оформить два отдельных пулл реквеста: для справочника пользователей и для верстки

2022-05-21 09:32 UTC, closed without merging