Fix login form
stpracticejob/job_2022 pull request #30
Opened 2022-06-04 19:01 UTC by sergeybe2

2022-06-05 07:18 UTC, MikhailSalkov commented
@NaikaMur уже добавила в #22 метод `Flight::accessDenied();`, который выводит страницу 403 ошибки, лучше использовать его. Файл с ошибкой `views/errors/403.php` тоже есть, его сразу менять.

2022-06-06 10:45 UTC, MikhailSalkov requested changes
@NaikaMur уже добавила в #22 метод `Flight::accessDenied();`, который выводит страницу 403 ошибки, лучше использовать его. Файл с ошибкой `views/errors/403.php` тоже есть, его сразу менять.

2022-06-07 21:01 UTC, sergeybe2 commented
> @NaikaMur уже добавила в #22 метод `Flight::accessDenied();`, который выводит страницу 403 ошибки, лучше использовать его. Файл с ошибкой `views/errors/403.php` тоже есть, его сразу менять.

Fixed.

2022-06-08 06:18 UTC, MikhailSalkov requested changes
Убрать дублирование стилей

2022-06-08 06:18 UTC, MikhailSalkov commented on views/main_page.php
>  		<link rel="stylesheet" href="/css/style.css"/>
Так как стили подключены в файле `head.inc.php`, можно убрать стили, чтобы не дублировались

2022-06-08 06:22 UTC, sergeybe2 commented on views/main_page.php
>  		<link rel="stylesheet" href="/css/style.css"/>
Ага, убрал.

2022-06-08 06:23 UTC, MikhailSalkov requested changes
Ошибка на странице 403 из-за некорректных инклудов

2022-06-08 06:23 UTC, MikhailSalkov commented on views/errors/403.php
> +		<? include('head.inc.php'); ?>
Еще не работают инклуды, надо добавить `../views/`

2022-06-08 06:27 UTC, MikhailSalkov approved these changes

2022-06-08 06:27 UTC, sergeybe2 commented on views/errors/403.php
> +		<? include('head.inc.php'); ?>
Добавил.

2022-06-08 06:27 UTC, merged